access_token = "access_token" # please set me up!

[destination.postgres.credentials]
database = "dlt_data" # please set me up!
password = "loader" # please set me up!
username = "loader" # please set me up!
host = "localhost" # please set me up!
port = 5432
connect_timeout = 15
